fix ?

diff --git a/docker/images/n8n/Dockerfile b/docker/images/n8n/Dockerfile
--- a/docker/images/n8n/Dockerfile
+++ b/docker/images/n8n/Dockerfile
@@ -3,14 +3,14 @@ ARG NODE_VERSION=20
 FROM koopernic/n8n-base-armv7:${NODE_VERSION}
 
 ARG N8N_VERSION=1.42.1
-#RUN if [ -z "$N8N_VERSION" ] ; then echo "The N8N_VERSION argument is missing!" ; exit 1; fi
+RUN if [ -z "$N8N_VERSION" ] ; then echo "The N8N_VERSION argument is missing!" ; exit 1; fi
 
 ENV N8N_VERSION=${N8N_VERSION}
 ENV NODE_ENV=production
 ENV N8N_RELEASE_TYPE=stable
 RUN set -eux; \
 	apk --no-cache add --virtual build-dependencies python3 build-base && \
-	npm install -g --omit=dev n8n@1.42.1 --ignore-scripts && \
+	npm install -g --omit=dev n8n@${N8N_VERSION} --ignore-scripts && \
 	apk del build-dependencies && \
 	npm rebuild --prefix=/usr/local/lib/node_modules/n8n sqlite3 && \	
 	rm -rf /usr/local/lib/node_modules/n8n/node_modules/@n8n/chat && \
